// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { deleteApiVbyVersionRegistrationDeleteById, deleteApiVbyVersionRegistrationDeleteMultiple, getApiVbyVersionAuthSetup2Fa, getApiVbyVersionRegistrationMyRegistrations, getApiVbyVersionRegistrationSingleById, getApiVbyVersionRegistrationStolen, getApiVbyVersionRegistrationStolenByUserId, getApiVbyVersionRegistrationUserRegistrationsByUserId, getApiVbyVersionUserGetAuthenticated, type Options, patchApiVbyVersionRegistrationMarkNotStolenById, patchApiVbyVersionRegistrationMarkStolenById, patchApiVbyVersionRegistrationUpdateById, postApiVbyVersionAuthDisable2Fa, postApiVbyVersionAuthEnable2Fa, postApiVbyVersionAuthLogin, postApiVbyVersionAuthRefresh, postApiVbyVersionAuthRegister, postApiVbyVersionAuthRevoke, postApiVbyVersionAuthVerify2Fa, postApiVbyVersionRegistrationAdd, postApiVbyVersionUserFinishProfileSetup } from '../sdk.gen';
import type { DeleteApiVbyVersionRegistrationDeleteByIdData, DeleteApiVbyVersionRegistrationDeleteMultipleData, GetApiVbyVersionAuthSetup2FaData, GetApiVbyVersionRegistrationMyRegistrationsData, GetApiVbyVersionRegistrationSingleByIdData, GetApiVbyVersionRegistrationStolenByUserIdData, GetApiVbyVersionRegistrationStolenData, GetApiVbyVersionRegistrationUserRegistrationsByUserIdData, GetApiVbyVersionUserGetAuthenticatedData, PatchApiVbyVersionRegistrationMarkNotStolenByIdData, PatchApiVbyVersionRegistrationMarkStolenByIdData, PatchApiVbyVersionRegistrationUpdateByIdData, PostApiVbyVersionAuthDisable2FaData, PostApiVbyVersionAuthEnable2FaData, PostApiVbyVersionAuthLoginData, PostApiVbyVersionAuthRefreshData, PostApiVbyVersionAuthRegisterData, PostApiVbyVersionAuthRevokeData, PostApiVbyVersionAuthVerify2FaData, PostApiVbyVersionRegistrationAddData, PostApiVbyVersionUserFinishProfileSetupData } from '../types.gen';

export const postApiVbyVersionAuthRegisterMutation = (options?: Partial<Options<PostApiVbyVersionAuthRegisterData>>): UseMutationOptions<unknown, DefaultError, Options<PostApiVbyVersionAuthRegisterData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PostApiVbyVersionAuthRegisterData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiVbyVersionAuthRegister({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postApiVbyVersionAuthLoginMutation = (options?: Partial<Options<PostApiVbyVersionAuthLoginData>>): UseMutationOptions<unknown, DefaultError, Options<PostApiVbyVersionAuthLoginData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PostApiVbyVersionAuthLoginData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiVbyVersionAuthLogin({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postApiVbyVersionAuthVerify2FaMutation = (options?: Partial<Options<PostApiVbyVersionAuthVerify2FaData>>): UseMutationOptions<unknown, DefaultError, Options<PostApiVbyVersionAuthVerify2FaData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PostApiVbyVersionAuthVerify2FaData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiVbyVersionAuthVerify2Fa({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getApiVbyVersionAuthSetup2FaQueryKey = (options: Options<GetApiVbyVersionAuthSetup2FaData>) => createQueryKey('getApiVbyVersionAuthSetup2Fa', options);

export const getApiVbyVersionAuthSetup2FaOptions = (options: Options<GetApiVbyVersionAuthSetup2FaData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getApiVbyVersionAuthSetup2FaQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiVbyVersionAuthSetup2Fa({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiVbyVersionAuthSetup2FaQueryKey(options)
});

export const postApiVbyVersionAuthEnable2FaMutation = (options?: Partial<Options<PostApiVbyVersionAuthEnable2FaData>>): UseMutationOptions<unknown, DefaultError, Options<PostApiVbyVersionAuthEnable2FaData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PostApiVbyVersionAuthEnable2FaData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiVbyVersionAuthEnable2Fa({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postApiVbyVersionAuthDisable2FaMutation = (options?: Partial<Options<PostApiVbyVersionAuthDisable2FaData>>): UseMutationOptions<unknown, DefaultError, Options<PostApiVbyVersionAuthDisable2FaData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PostApiVbyVersionAuthDisable2FaData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiVbyVersionAuthDisable2Fa({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postApiVbyVersionAuthRefreshMutation = (options?: Partial<Options<PostApiVbyVersionAuthRefreshData>>): UseMutationOptions<unknown, DefaultError, Options<PostApiVbyVersionAuthRefreshData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PostApiVbyVersionAuthRefreshData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiVbyVersionAuthRefresh({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postApiVbyVersionAuthRevokeMutation = (options?: Partial<Options<PostApiVbyVersionAuthRevokeData>>): UseMutationOptions<unknown, DefaultError, Options<PostApiVbyVersionAuthRevokeData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PostApiVbyVersionAuthRevokeData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiVbyVersionAuthRevoke({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postApiVbyVersionRegistrationAddMutation = (options?: Partial<Options<PostApiVbyVersionRegistrationAddData>>): UseMutationOptions<unknown, DefaultError, Options<PostApiVbyVersionRegistrationAddData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PostApiVbyVersionRegistrationAddData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiVbyVersionRegistrationAdd({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getApiVbyVersionRegistrationMyRegistrationsQueryKey = (options: Options<GetApiVbyVersionRegistrationMyRegistrationsData>) => createQueryKey('getApiVbyVersionRegistrationMyRegistrations', options);

export const getApiVbyVersionRegistrationMyRegistrationsOptions = (options: Options<GetApiVbyVersionRegistrationMyRegistrationsData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getApiVbyVersionRegistrationMyRegistrationsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiVbyVersionRegistrationMyRegistrations({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiVbyVersionRegistrationMyRegistrationsQueryKey(options)
});

export const getApiVbyVersionRegistrationUserRegistrationsByUserIdQueryKey = (options: Options<GetApiVbyVersionRegistrationUserRegistrationsByUserIdData>) => createQueryKey('getApiVbyVersionRegistrationUserRegistrationsByUserId', options);

export const getApiVbyVersionRegistrationUserRegistrationsByUserIdOptions = (options: Options<GetApiVbyVersionRegistrationUserRegistrationsByUserIdData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getApiVbyVersionRegistrationUserRegistrationsByUserIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiVbyVersionRegistrationUserRegistrationsByUserId({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiVbyVersionRegistrationUserRegistrationsByUserIdQueryKey(options)
});

export const getApiVbyVersionRegistrationStolenQueryKey = (options: Options<GetApiVbyVersionRegistrationStolenData>) => createQueryKey('getApiVbyVersionRegistrationStolen', options);

export const getApiVbyVersionRegistrationStolenOptions = (options: Options<GetApiVbyVersionRegistrationStolenData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getApiVbyVersionRegistrationStolenQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiVbyVersionRegistrationStolen({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiVbyVersionRegistrationStolenQueryKey(options)
});

export const getApiVbyVersionRegistrationStolenByUserIdQueryKey = (options: Options<GetApiVbyVersionRegistrationStolenByUserIdData>) => createQueryKey('getApiVbyVersionRegistrationStolenByUserId', options);

export const getApiVbyVersionRegistrationStolenByUserIdOptions = (options: Options<GetApiVbyVersionRegistrationStolenByUserIdData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getApiVbyVersionRegistrationStolenByUserIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiVbyVersionRegistrationStolenByUserId({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiVbyVersionRegistrationStolenByUserIdQueryKey(options)
});

export const getApiVbyVersionRegistrationSingleByIdQueryKey = (options: Options<GetApiVbyVersionRegistrationSingleByIdData>) => createQueryKey('getApiVbyVersionRegistrationSingleById', options);

export const getApiVbyVersionRegistrationSingleByIdOptions = (options: Options<GetApiVbyVersionRegistrationSingleByIdData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getApiVbyVersionRegistrationSingleByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiVbyVersionRegistrationSingleById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiVbyVersionRegistrationSingleByIdQueryKey(options)
});

export const patchApiVbyVersionRegistrationMarkStolenByIdMutation = (options?: Partial<Options<PatchApiVbyVersionRegistrationMarkStolenByIdData>>): UseMutationOptions<unknown, DefaultError, Options<PatchApiVbyVersionRegistrationMarkStolenByIdData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PatchApiVbyVersionRegistrationMarkStolenByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await patchApiVbyVersionRegistrationMarkStolenById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const patchApiVbyVersionRegistrationMarkNotStolenByIdMutation = (options?: Partial<Options<PatchApiVbyVersionRegistrationMarkNotStolenByIdData>>): UseMutationOptions<unknown, DefaultError, Options<PatchApiVbyVersionRegistrationMarkNotStolenByIdData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PatchApiVbyVersionRegistrationMarkNotStolenByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await patchApiVbyVersionRegistrationMarkNotStolenById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const patchApiVbyVersionRegistrationUpdateByIdMutation = (options?: Partial<Options<PatchApiVbyVersionRegistrationUpdateByIdData>>): UseMutationOptions<unknown, DefaultError, Options<PatchApiVbyVersionRegistrationUpdateByIdData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PatchApiVbyVersionRegistrationUpdateByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await patchApiVbyVersionRegistrationUpdateById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const deleteApiVbyVersionRegistrationDeleteByIdMutation = (options?: Partial<Options<DeleteApiVbyVersionRegistrationDeleteByIdData>>): UseMutationOptions<unknown, DefaultError, Options<DeleteApiVbyVersionRegistrationDeleteByIdData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<DeleteApiVbyVersionRegistrationDeleteByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteApiVbyVersionRegistrationDeleteById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const deleteApiVbyVersionRegistrationDeleteMultipleMutation = (options?: Partial<Options<DeleteApiVbyVersionRegistrationDeleteMultipleData>>): UseMutationOptions<unknown, DefaultError, Options<DeleteApiVbyVersionRegistrationDeleteMultipleData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<DeleteApiVbyVersionRegistrationDeleteMultipleData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteApiVbyVersionRegistrationDeleteMultiple({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getApiVbyVersionUserGetAuthenticatedQueryKey = (options: Options<GetApiVbyVersionUserGetAuthenticatedData>) => createQueryKey('getApiVbyVersionUserGetAuthenticated', options);

export const getApiVbyVersionUserGetAuthenticatedOptions = (options: Options<GetApiVbyVersionUserGetAuthenticatedData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof getApiVbyVersionUserGetAuthenticatedQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiVbyVersionUserGetAuthenticated({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiVbyVersionUserGetAuthenticatedQueryKey(options)
});

export const postApiVbyVersionUserFinishProfileSetupMutation = (options?: Partial<Options<PostApiVbyVersionUserFinishProfileSetupData>>): UseMutationOptions<unknown, DefaultError, Options<PostApiVbyVersionUserFinishProfileSetupData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PostApiVbyVersionUserFinishProfileSetupData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiVbyVersionUserFinishProfileSetup({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
