// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { addRegistration, authenticatedUser, deleteMultipleRegistration, deleteRegistration, disable2Fa, eable2Fa, finishProfileSetup, login, markNotStolen, markStolen, myRegistrations, type Options, refreshLogin, register, revokeRefresh, setup2Fa, singleRegistration, stolenRegistrations, stolenUserRegistrations, updateRegistration, uploadRegistrationImages, userRegistrations, verify2Fa } from '../sdk.gen';
import type { AddRegistrationData, AuthenticatedUserData, DeleteMultipleRegistrationData, DeleteRegistrationData, Disable2FaData, Eable2FaData, FinishProfileSetupData, LoginData, MarkNotStolenData, MarkStolenData, MyRegistrationsData, RefreshLoginData, RegisterData, RevokeRefreshData, Setup2FaData, SingleRegistrationData, StolenRegistrationsData, StolenUserRegistrationsData, UpdateRegistrationData, UploadRegistrationImagesData, UserRegistrationsData, Verify2FaData } from '../types.gen';

export const registerMutation = (options?: Partial<Options<RegisterData>>): UseMutationOptions<unknown, DefaultError, Options<RegisterData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<RegisterData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await register({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const loginMutation = (options?: Partial<Options<LoginData>>): UseMutationOptions<unknown, DefaultError, Options<LoginData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<LoginData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await login({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const verify2FaMutation = (options?: Partial<Options<Verify2FaData>>): UseMutationOptions<unknown, DefaultError, Options<Verify2FaData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<Verify2FaData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await verify2Fa({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const setup2FaQueryKey = (options: Options<Setup2FaData>) => createQueryKey('setup2Fa', options);

export const setup2FaOptions = (options: Options<Setup2FaData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof setup2FaQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await setup2Fa({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: setup2FaQueryKey(options)
});

export const eable2FaMutation = (options?: Partial<Options<Eable2FaData>>): UseMutationOptions<unknown, DefaultError, Options<Eable2FaData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<Eable2FaData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await eable2Fa({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const disable2FaMutation = (options?: Partial<Options<Disable2FaData>>): UseMutationOptions<unknown, DefaultError, Options<Disable2FaData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<Disable2FaData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await disable2Fa({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const refreshLoginMutation = (options?: Partial<Options<RefreshLoginData>>): UseMutationOptions<unknown, DefaultError, Options<RefreshLoginData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<RefreshLoginData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await refreshLogin({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const revokeRefreshMutation = (options?: Partial<Options<RevokeRefreshData>>): UseMutationOptions<unknown, DefaultError, Options<RevokeRefreshData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<RevokeRefreshData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await revokeRefresh({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const uploadRegistrationImagesMutation = (options?: Partial<Options<UploadRegistrationImagesData>>): UseMutationOptions<unknown, DefaultError, Options<UploadRegistrationImagesData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<UploadRegistrationImagesData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await uploadRegistrationImages({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const addRegistrationMutation = (options?: Partial<Options<AddRegistrationData>>): UseMutationOptions<unknown, DefaultError, Options<AddRegistrationData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<AddRegistrationData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await addRegistration({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const myRegistrationsQueryKey = (options: Options<MyRegistrationsData>) => createQueryKey('myRegistrations', options);

export const myRegistrationsOptions = (options: Options<MyRegistrationsData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof myRegistrationsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await myRegistrations({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: myRegistrationsQueryKey(options)
});

export const userRegistrationsQueryKey = (options: Options<UserRegistrationsData>) => createQueryKey('userRegistrations', options);

export const userRegistrationsOptions = (options: Options<UserRegistrationsData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof userRegistrationsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await userRegistrations({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: userRegistrationsQueryKey(options)
});

export const stolenRegistrationsQueryKey = (options: Options<StolenRegistrationsData>) => createQueryKey('stolenRegistrations', options);

export const stolenRegistrationsOptions = (options: Options<StolenRegistrationsData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof stolenRegistrationsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await stolenRegistrations({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: stolenRegistrationsQueryKey(options)
});

export const stolenUserRegistrationsQueryKey = (options: Options<StolenUserRegistrationsData>) => createQueryKey('stolenUserRegistrations', options);

export const stolenUserRegistrationsOptions = (options: Options<StolenUserRegistrationsData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof stolenUserRegistrationsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await stolenUserRegistrations({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: stolenUserRegistrationsQueryKey(options)
});

export const singleRegistrationQueryKey = (options: Options<SingleRegistrationData>) => createQueryKey('singleRegistration', options);

export const singleRegistrationOptions = (options: Options<SingleRegistrationData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof singleRegistrationQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await singleRegistration({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: singleRegistrationQueryKey(options)
});

export const markStolenMutation = (options?: Partial<Options<MarkStolenData>>): UseMutationOptions<unknown, DefaultError, Options<MarkStolenData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<MarkStolenData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await markStolen({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const markNotStolenMutation = (options?: Partial<Options<MarkNotStolenData>>): UseMutationOptions<unknown, DefaultError, Options<MarkNotStolenData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<MarkNotStolenData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await markNotStolen({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const updateRegistrationMutation = (options?: Partial<Options<UpdateRegistrationData>>): UseMutationOptions<unknown, DefaultError, Options<UpdateRegistrationData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<UpdateRegistrationData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateRegistration({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const deleteRegistrationMutation = (options?: Partial<Options<DeleteRegistrationData>>): UseMutationOptions<unknown, DefaultError, Options<DeleteRegistrationData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<DeleteRegistrationData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteRegistration({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const deleteMultipleRegistrationMutation = (options?: Partial<Options<DeleteMultipleRegistrationData>>): UseMutationOptions<unknown, DefaultError, Options<DeleteMultipleRegistrationData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<DeleteMultipleRegistrationData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteMultipleRegistration({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const authenticatedUserQueryKey = (options: Options<AuthenticatedUserData>) => createQueryKey('authenticatedUser', options);

export const authenticatedUserOptions = (options: Options<AuthenticatedUserData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof authenticatedUserQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await authenticatedUser({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: authenticatedUserQueryKey(options)
});

export const finishProfileSetupMutation = (options?: Partial<Options<FinishProfileSetupData>>): UseMutationOptions<unknown, DefaultError, Options<FinishProfileSetupData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<FinishProfileSetupData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await finishProfileSetup({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
