// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteApiVbyVersionRegistrationDeleteByIdData, DeleteApiVbyVersionRegistrationDeleteByIdResponses, DeleteApiVbyVersionRegistrationDeleteMultipleData, DeleteApiVbyVersionRegistrationDeleteMultipleResponses, GetApiVbyVersionAuthSetup2FaData, GetApiVbyVersionAuthSetup2FaResponses, GetApiVbyVersionRegistrationMyRegistrationsData, GetApiVbyVersionRegistrationMyRegistrationsResponses, GetApiVbyVersionRegistrationSingleByIdData, GetApiVbyVersionRegistrationSingleByIdResponses, GetApiVbyVersionRegistrationStolenByUserIdData, GetApiVbyVersionRegistrationStolenByUserIdResponses, GetApiVbyVersionRegistrationStolenData, GetApiVbyVersionRegistrationStolenResponses, GetApiVbyVersionRegistrationUserRegistrationsByUserIdData, GetApiVbyVersionRegistrationUserRegistrationsByUserIdResponses, GetApiVbyVersionUserGetAuthenticatedData, GetApiVbyVersionUserGetAuthenticatedResponses, PatchApiVbyVersionRegistrationMarkNotStolenByIdData, PatchApiVbyVersionRegistrationMarkNotStolenByIdResponses, PatchApiVbyVersionRegistrationMarkStolenByIdData, PatchApiVbyVersionRegistrationMarkStolenByIdResponses, PatchApiVbyVersionRegistrationUpdateByIdData, PatchApiVbyVersionRegistrationUpdateByIdResponses, PostApiVbyVersionAuthDisable2FaData, PostApiVbyVersionAuthDisable2FaResponses, PostApiVbyVersionAuthEnable2FaData, PostApiVbyVersionAuthEnable2FaResponses, PostApiVbyVersionAuthLoginData, PostApiVbyVersionAuthLoginResponses, PostApiVbyVersionAuthRefreshData, PostApiVbyVersionAuthRefreshResponses, PostApiVbyVersionAuthRegisterData, PostApiVbyVersionAuthRegisterResponses, PostApiVbyVersionAuthRevokeData, PostApiVbyVersionAuthRevokeResponses, PostApiVbyVersionAuthVerify2FaData, PostApiVbyVersionAuthVerify2FaResponses, PostApiVbyVersionRegistrationAddData, PostApiVbyVersionRegistrationAddResponses, PostApiVbyVersionUserFinishProfileSetupData, PostApiVbyVersionUserFinishProfileSetupResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const postApiVbyVersionAuthRegister = <ThrowOnError extends boolean = false>(options: Options<PostApiVbyVersionAuthRegisterData, ThrowOnError>) => (options.client ?? client).post<PostApiVbyVersionAuthRegisterResponses, unknown, ThrowOnError>({
    url: '/api/v{version}/Auth/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postApiVbyVersionAuthLogin = <ThrowOnError extends boolean = false>(options: Options<PostApiVbyVersionAuthLoginData, ThrowOnError>) => (options.client ?? client).post<PostApiVbyVersionAuthLoginResponses, unknown, ThrowOnError>({
    url: '/api/v{version}/Auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postApiVbyVersionAuthVerify2Fa = <ThrowOnError extends boolean = false>(options: Options<PostApiVbyVersionAuthVerify2FaData, ThrowOnError>) => (options.client ?? client).post<PostApiVbyVersionAuthVerify2FaResponses, unknown, ThrowOnError>({
    url: '/api/v{version}/Auth/verify-2fa',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getApiVbyVersionAuthSetup2Fa = <ThrowOnError extends boolean = false>(options: Options<GetApiVbyVersionAuthSetup2FaData, ThrowOnError>) => (options.client ?? client).get<GetApiVbyVersionAuthSetup2FaResponses, unknown, ThrowOnError>({ url: '/api/v{version}/Auth/setup-2fa', ...options });

export const postApiVbyVersionAuthEnable2Fa = <ThrowOnError extends boolean = false>(options: Options<PostApiVbyVersionAuthEnable2FaData, ThrowOnError>) => (options.client ?? client).post<PostApiVbyVersionAuthEnable2FaResponses, unknown, ThrowOnError>({
    url: '/api/v{version}/Auth/enable-2fa',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postApiVbyVersionAuthDisable2Fa = <ThrowOnError extends boolean = false>(options: Options<PostApiVbyVersionAuthDisable2FaData, ThrowOnError>) => (options.client ?? client).post<PostApiVbyVersionAuthDisable2FaResponses, unknown, ThrowOnError>({ url: '/api/v{version}/Auth/disable-2fa', ...options });

export const postApiVbyVersionAuthRefresh = <ThrowOnError extends boolean = false>(options: Options<PostApiVbyVersionAuthRefreshData, ThrowOnError>) => (options.client ?? client).post<PostApiVbyVersionAuthRefreshResponses, unknown, ThrowOnError>({
    url: '/api/v{version}/Auth/refresh',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postApiVbyVersionAuthRevoke = <ThrowOnError extends boolean = false>(options: Options<PostApiVbyVersionAuthRevokeData, ThrowOnError>) => (options.client ?? client).post<PostApiVbyVersionAuthRevokeResponses, unknown, ThrowOnError>({
    url: '/api/v{version}/Auth/revoke',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postApiVbyVersionRegistrationAdd = <ThrowOnError extends boolean = false>(options: Options<PostApiVbyVersionRegistrationAddData, ThrowOnError>) => (options.client ?? client).post<PostApiVbyVersionRegistrationAddResponses, unknown, ThrowOnError>({
    url: '/api/v{version}/Registration/add',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getApiVbyVersionRegistrationMyRegistrations = <ThrowOnError extends boolean = false>(options: Options<GetApiVbyVersionRegistrationMyRegistrationsData, ThrowOnError>) => (options.client ?? client).get<GetApiVbyVersionRegistrationMyRegistrationsResponses, unknown, ThrowOnError>({ url: '/api/v{version}/Registration/my-registrations', ...options });

export const getApiVbyVersionRegistrationUserRegistrationsByUserId = <ThrowOnError extends boolean = false>(options: Options<GetApiVbyVersionRegistrationUserRegistrationsByUserIdData, ThrowOnError>) => (options.client ?? client).get<GetApiVbyVersionRegistrationUserRegistrationsByUserIdResponses, unknown, ThrowOnError>({ url: '/api/v{version}/Registration/user-registrations/{userId}', ...options });

export const getApiVbyVersionRegistrationStolen = <ThrowOnError extends boolean = false>(options: Options<GetApiVbyVersionRegistrationStolenData, ThrowOnError>) => (options.client ?? client).get<GetApiVbyVersionRegistrationStolenResponses, unknown, ThrowOnError>({ url: '/api/v{version}/Registration/stolen', ...options });

export const getApiVbyVersionRegistrationStolenByUserId = <ThrowOnError extends boolean = false>(options: Options<GetApiVbyVersionRegistrationStolenByUserIdData, ThrowOnError>) => (options.client ?? client).get<GetApiVbyVersionRegistrationStolenByUserIdResponses, unknown, ThrowOnError>({ url: '/api/v{version}/Registration/stolen/{userId}', ...options });

export const getApiVbyVersionRegistrationSingleById = <ThrowOnError extends boolean = false>(options: Options<GetApiVbyVersionRegistrationSingleByIdData, ThrowOnError>) => (options.client ?? client).get<GetApiVbyVersionRegistrationSingleByIdResponses, unknown, ThrowOnError>({ url: '/api/v{version}/Registration/single/{id}', ...options });

export const patchApiVbyVersionRegistrationMarkStolenById = <ThrowOnError extends boolean = false>(options: Options<PatchApiVbyVersionRegistrationMarkStolenByIdData, ThrowOnError>) => (options.client ?? client).patch<PatchApiVbyVersionRegistrationMarkStolenByIdResponses, unknown, ThrowOnError>({ url: '/api/v{version}/Registration/mark-stolen/{id}', ...options });

export const patchApiVbyVersionRegistrationMarkNotStolenById = <ThrowOnError extends boolean = false>(options: Options<PatchApiVbyVersionRegistrationMarkNotStolenByIdData, ThrowOnError>) => (options.client ?? client).patch<PatchApiVbyVersionRegistrationMarkNotStolenByIdResponses, unknown, ThrowOnError>({ url: '/api/v{version}/Registration/mark-not-stolen/{id}', ...options });

export const patchApiVbyVersionRegistrationUpdateById = <ThrowOnError extends boolean = false>(options: Options<PatchApiVbyVersionRegistrationUpdateByIdData, ThrowOnError>) => (options.client ?? client).patch<PatchApiVbyVersionRegistrationUpdateByIdResponses, unknown, ThrowOnError>({
    url: '/api/v{version}/Registration/update/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deleteApiVbyVersionRegistrationDeleteById = <ThrowOnError extends boolean = false>(options: Options<DeleteApiVbyVersionRegistrationDeleteByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteApiVbyVersionRegistrationDeleteByIdResponses, unknown, ThrowOnError>({ url: '/api/v{version}/Registration/delete/{id}', ...options });

export const deleteApiVbyVersionRegistrationDeleteMultiple = <ThrowOnError extends boolean = false>(options: Options<DeleteApiVbyVersionRegistrationDeleteMultipleData, ThrowOnError>) => (options.client ?? client).delete<DeleteApiVbyVersionRegistrationDeleteMultipleResponses, unknown, ThrowOnError>({
    url: '/api/v{version}/Registration/delete-multiple',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getApiVbyVersionUserGetAuthenticated = <ThrowOnError extends boolean = false>(options: Options<GetApiVbyVersionUserGetAuthenticatedData, ThrowOnError>) => (options.client ?? client).get<GetApiVbyVersionUserGetAuthenticatedResponses, unknown, ThrowOnError>({ url: '/api/v{version}/User/get-authenticated', ...options });

export const postApiVbyVersionUserFinishProfileSetup = <ThrowOnError extends boolean = false>(options: Options<PostApiVbyVersionUserFinishProfileSetupData, ThrowOnError>) => (options.client ?? client).post<PostApiVbyVersionUserFinishProfileSetupResponses, unknown, ThrowOnError>({
    url: '/api/v{version}/User/finish-profile-setup',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
