// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { AddRegistrationData, AddRegistrationResponses, AuthenticatedUserData, AuthenticatedUserResponses, DeleteMultipleRegistrationData, DeleteMultipleRegistrationResponses, DeleteRegistrationData, DeleteRegistrationResponses, Disable2FaData, Disable2FaResponses, Eable2FaData, Eable2FaResponses, FinishProfileSetupData, FinishProfileSetupResponses, LoginData, LoginResponses, MarkNotStolenData, MarkNotStolenResponses, MarkStolenData, MarkStolenResponses, MyRegistrationsData, MyRegistrationsResponses, RefreshLoginData, RefreshLoginResponses, RegisterData, RegisterResponses, RevokeRefreshData, RevokeRefreshResponses, Setup2FaData, Setup2FaResponses, SingleRegistrationData, SingleRegistrationResponses, StolenRegistrationsData, StolenRegistrationsResponses, StolenUserRegistrationsData, StolenUserRegistrationsResponses, UpdateRegistrationData, UpdateRegistrationResponses, UploadRegistrationImagesData, UploadRegistrationImagesResponses, UserRegistrationsData, UserRegistrationsResponses, Verify2FaData, Verify2FaResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const register = <ThrowOnError extends boolean = false>(options: Options<RegisterData, ThrowOnError>) => (options.client ?? client).post<RegisterResponses, unknown, ThrowOnError>({
    url: '/api/v{version}/Auth/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const login = <ThrowOnError extends boolean = false>(options: Options<LoginData, ThrowOnError>) => (options.client ?? client).post<LoginResponses, unknown, ThrowOnError>({
    url: '/api/v{version}/Auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const verify2Fa = <ThrowOnError extends boolean = false>(options: Options<Verify2FaData, ThrowOnError>) => (options.client ?? client).post<Verify2FaResponses, unknown, ThrowOnError>({
    url: '/api/v{version}/Auth/verify-2fa',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const setup2Fa = <ThrowOnError extends boolean = false>(options: Options<Setup2FaData, ThrowOnError>) => (options.client ?? client).get<Setup2FaResponses, unknown, ThrowOnError>({ url: '/api/v{version}/Auth/setup-2fa', ...options });

export const eable2Fa = <ThrowOnError extends boolean = false>(options: Options<Eable2FaData, ThrowOnError>) => (options.client ?? client).post<Eable2FaResponses, unknown, ThrowOnError>({
    url: '/api/v{version}/Auth/enable-2fa',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const disable2Fa = <ThrowOnError extends boolean = false>(options: Options<Disable2FaData, ThrowOnError>) => (options.client ?? client).post<Disable2FaResponses, unknown, ThrowOnError>({ url: '/api/v{version}/Auth/disable-2fa', ...options });

export const refreshLogin = <ThrowOnError extends boolean = false>(options: Options<RefreshLoginData, ThrowOnError>) => (options.client ?? client).post<RefreshLoginResponses, unknown, ThrowOnError>({
    url: '/api/v{version}/Auth/refresh',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const revokeRefresh = <ThrowOnError extends boolean = false>(options: Options<RevokeRefreshData, ThrowOnError>) => (options.client ?? client).post<RevokeRefreshResponses, unknown, ThrowOnError>({
    url: '/api/v{version}/Auth/revoke',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const uploadRegistrationImages = <ThrowOnError extends boolean = false>(options: Options<UploadRegistrationImagesData, ThrowOnError>) => (options.client ?? client).post<UploadRegistrationImagesResponses, unknown, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/api/v{version}/Image/upload/{registrationId}',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

export const addRegistration = <ThrowOnError extends boolean = false>(options: Options<AddRegistrationData, ThrowOnError>) => (options.client ?? client).post<AddRegistrationResponses, unknown, ThrowOnError>({
    url: '/api/v{version}/Registration/add',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const myRegistrations = <ThrowOnError extends boolean = false>(options: Options<MyRegistrationsData, ThrowOnError>) => (options.client ?? client).get<MyRegistrationsResponses, unknown, ThrowOnError>({ url: '/api/v{version}/Registration/my-registrations', ...options });

export const userRegistrations = <ThrowOnError extends boolean = false>(options: Options<UserRegistrationsData, ThrowOnError>) => (options.client ?? client).get<UserRegistrationsResponses, unknown, ThrowOnError>({ url: '/api/v{version}/Registration/user-registrations/{userId}', ...options });

export const stolenRegistrations = <ThrowOnError extends boolean = false>(options: Options<StolenRegistrationsData, ThrowOnError>) => (options.client ?? client).get<StolenRegistrationsResponses, unknown, ThrowOnError>({ url: '/api/v{version}/Registration/stolen', ...options });

export const stolenUserRegistrations = <ThrowOnError extends boolean = false>(options: Options<StolenUserRegistrationsData, ThrowOnError>) => (options.client ?? client).get<StolenUserRegistrationsResponses, unknown, ThrowOnError>({ url: '/api/v{version}/Registration/stolen/{userId}', ...options });

export const singleRegistration = <ThrowOnError extends boolean = false>(options: Options<SingleRegistrationData, ThrowOnError>) => (options.client ?? client).get<SingleRegistrationResponses, unknown, ThrowOnError>({ url: '/api/v{version}/Registration/single/{id}', ...options });

export const markStolen = <ThrowOnError extends boolean = false>(options: Options<MarkStolenData, ThrowOnError>) => (options.client ?? client).patch<MarkStolenResponses, unknown, ThrowOnError>({ url: '/api/v{version}/Registration/mark-stolen/{id}', ...options });

export const markNotStolen = <ThrowOnError extends boolean = false>(options: Options<MarkNotStolenData, ThrowOnError>) => (options.client ?? client).patch<MarkNotStolenResponses, unknown, ThrowOnError>({ url: '/api/v{version}/Registration/mark-not-stolen/{id}', ...options });

export const updateRegistration = <ThrowOnError extends boolean = false>(options: Options<UpdateRegistrationData, ThrowOnError>) => (options.client ?? client).patch<UpdateRegistrationResponses, unknown, ThrowOnError>({
    url: '/api/v{version}/Registration/update/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deleteRegistration = <ThrowOnError extends boolean = false>(options: Options<DeleteRegistrationData, ThrowOnError>) => (options.client ?? client).delete<DeleteRegistrationResponses, unknown, ThrowOnError>({ url: '/api/v{version}/Registration/delete/{id}', ...options });

export const deleteMultipleRegistration = <ThrowOnError extends boolean = false>(options: Options<DeleteMultipleRegistrationData, ThrowOnError>) => (options.client ?? client).delete<DeleteMultipleRegistrationResponses, unknown, ThrowOnError>({
    url: '/api/v{version}/Registration/delete-multiple',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const authenticatedUser = <ThrowOnError extends boolean = false>(options: Options<AuthenticatedUserData, ThrowOnError>) => (options.client ?? client).get<AuthenticatedUserResponses, unknown, ThrowOnError>({ url: '/api/v{version}/User/get-authenticated', ...options });

export const finishProfileSetup = <ThrowOnError extends boolean = false>(options: Options<FinishProfileSetupData, ThrowOnError>) => (options.client ?? client).post<FinishProfileSetupResponses, unknown, ThrowOnError>({
    url: '/api/v{version}/User/finish-profile-setup',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
