// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:26786/' | (string & {});
};

export type CreateRegistrationDto = {
    model?: null | string;
    brand?: string;
    modelYear?: null | number | string;
    frameSize?: number | string;
    frameSizeUnit?: FrameSizeUnit;
    frameType?: FrameType;
    primaryColour?: string;
    secondaryColour?: string;
    serialNumber?: string;
    city?: string;
    district?: null | string;
    description?: null | string;
    isStolen?: boolean;
    dateStolen?: null | string;
};

export type FinishProfileSetupDto = {
    name: string;
    phoneNumber?: string;
    profilePhotoUrl?: null | string;
};

export type FrameSizeUnit = number;

export type FrameType = number;

export type JwtRefreshRequest = {
    refreshToken?: string;
};

export type LoginDto = {
    email?: null | string;
    userName?: null | string;
    password: string;
};

export type RegisterDto = {
    email: string;
    userName: string;
    password: string;
};

export type TwoFactorDto = {
    email?: null | string;
    userName?: null | string;
    code?: string;
};

export type UpdateRegistrationDto = {
    model?: null | string;
    brand?: string;
    modelYear?: null | number | string;
    frameSize?: number | string;
    frameSizeUnit?: FrameSizeUnit;
    frameType?: FrameType;
    primaryColour?: string;
    secondaryColour?: string;
    city?: string;
    district?: null | string;
    description?: null | string;
};

export type VerifyTwoFactorDto = {
    code?: string;
};

export type PostApiVbyVersionAuthRegisterData = {
    body: RegisterDto;
    path: {
        version: string;
    };
    query?: never;
    url: '/api/v{version}/Auth/register';
};

export type PostApiVbyVersionAuthRegisterResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiVbyVersionAuthLoginData = {
    body: LoginDto;
    path: {
        version: string;
    };
    query?: never;
    url: '/api/v{version}/Auth/login';
};

export type PostApiVbyVersionAuthLoginResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiVbyVersionAuthVerify2FaData = {
    body: TwoFactorDto;
    path: {
        version: string;
    };
    query?: never;
    url: '/api/v{version}/Auth/verify-2fa';
};

export type PostApiVbyVersionAuthVerify2FaResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiVbyVersionAuthSetup2FaData = {
    body?: never;
    path: {
        version: string;
    };
    query?: never;
    url: '/api/v{version}/Auth/setup-2fa';
};

export type GetApiVbyVersionAuthSetup2FaResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiVbyVersionAuthEnable2FaData = {
    body: VerifyTwoFactorDto;
    path: {
        version: string;
    };
    query?: never;
    url: '/api/v{version}/Auth/enable-2fa';
};

export type PostApiVbyVersionAuthEnable2FaResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiVbyVersionAuthDisable2FaData = {
    body?: never;
    path: {
        version: string;
    };
    query?: never;
    url: '/api/v{version}/Auth/disable-2fa';
};

export type PostApiVbyVersionAuthDisable2FaResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiVbyVersionAuthRefreshData = {
    body?: null | JwtRefreshRequest;
    path: {
        version: string;
    };
    query?: never;
    url: '/api/v{version}/Auth/refresh';
};

export type PostApiVbyVersionAuthRefreshResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiVbyVersionAuthRevokeData = {
    body?: null | JwtRefreshRequest;
    path: {
        version: string;
    };
    query?: never;
    url: '/api/v{version}/Auth/revoke';
};

export type PostApiVbyVersionAuthRevokeResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiVbyVersionRegistrationAddData = {
    body: CreateRegistrationDto;
    path: {
        version: string;
    };
    query?: never;
    url: '/api/v{version}/Registration/add';
};

export type PostApiVbyVersionRegistrationAddResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiVbyVersionRegistrationMyRegistrationsData = {
    body?: never;
    path: {
        version: string;
    };
    query?: never;
    url: '/api/v{version}/Registration/my-registrations';
};

export type GetApiVbyVersionRegistrationMyRegistrationsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiVbyVersionRegistrationUserRegistrationsByUserIdData = {
    body?: never;
    path: {
        userId: string;
        version: string;
    };
    query?: never;
    url: '/api/v{version}/Registration/user-registrations/{userId}';
};

export type GetApiVbyVersionRegistrationUserRegistrationsByUserIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiVbyVersionRegistrationStolenData = {
    body?: never;
    path: {
        version: string;
    };
    query?: {
        Brand?: string;
        City?: string;
        SerialNumber?: string;
    };
    url: '/api/v{version}/Registration/stolen';
};

export type GetApiVbyVersionRegistrationStolenResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiVbyVersionRegistrationStolenByUserIdData = {
    body?: never;
    path: {
        userId: string;
        version: string;
    };
    query?: never;
    url: '/api/v{version}/Registration/stolen/{userId}';
};

export type GetApiVbyVersionRegistrationStolenByUserIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiVbyVersionRegistrationSingleByIdData = {
    body?: never;
    path: {
        id: string;
        version: string;
    };
    query?: never;
    url: '/api/v{version}/Registration/single/{id}';
};

export type GetApiVbyVersionRegistrationSingleByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PatchApiVbyVersionRegistrationMarkStolenByIdData = {
    body?: never;
    path: {
        id: string;
        version: string;
    };
    query?: never;
    url: '/api/v{version}/Registration/mark-stolen/{id}';
};

export type PatchApiVbyVersionRegistrationMarkStolenByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PatchApiVbyVersionRegistrationMarkNotStolenByIdData = {
    body?: never;
    path: {
        id: string;
        version: string;
    };
    query?: never;
    url: '/api/v{version}/Registration/mark-not-stolen/{id}';
};

export type PatchApiVbyVersionRegistrationMarkNotStolenByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PatchApiVbyVersionRegistrationUpdateByIdData = {
    body: UpdateRegistrationDto;
    path: {
        id: string;
        version: string;
    };
    query?: never;
    url: '/api/v{version}/Registration/update/{id}';
};

export type PatchApiVbyVersionRegistrationUpdateByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteApiVbyVersionRegistrationDeleteByIdData = {
    body?: never;
    path: {
        id: string;
        version: string;
    };
    query?: never;
    url: '/api/v{version}/Registration/delete/{id}';
};

export type DeleteApiVbyVersionRegistrationDeleteByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteApiVbyVersionRegistrationDeleteMultipleData = {
    body: Array<string>;
    path: {
        version: string;
    };
    query?: never;
    url: '/api/v{version}/Registration/delete-multiple';
};

export type DeleteApiVbyVersionRegistrationDeleteMultipleResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiVbyVersionUserGetAuthenticatedData = {
    body?: never;
    path: {
        version: string;
    };
    query?: never;
    url: '/api/v{version}/User/get-authenticated';
};

export type GetApiVbyVersionUserGetAuthenticatedResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiVbyVersionUserFinishProfileSetupData = {
    body: FinishProfileSetupDto;
    path: {
        version: string;
    };
    query?: never;
    url: '/api/v{version}/User/finish-profile-setup';
};

export type PostApiVbyVersionUserFinishProfileSetupResponses = {
    /**
     * OK
     */
    200: unknown;
};
