// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:26786/' | (string & {});
};

export type CreateRegistrationDto = {
    model?: null | string;
    brand?: string;
    modelYear?: null | number | string;
    frameSize?: number | string;
    frameSizeUnit?: FrameSizeUnit;
    frameType?: FrameType;
    primaryColour?: string;
    secondaryColour?: string;
    serialNumber?: string;
    city?: string;
    district?: null | string;
    description?: null | string;
    isStolen?: boolean;
    dateStolen?: null | string;
};

export type FinishProfileSetupDto = {
    name: string;
    phoneNumber?: string;
    profilePhotoUrl?: null | string;
};

export type FrameSizeUnit = number;

export type FrameType = number;

export type JwtRefreshRequest = {
    refreshToken?: string;
};

export type LoginDto = {
    email?: null | string;
    userName?: null | string;
    password: string;
};

export type RegisterDto = {
    email: string;
    userName: string;
    password: string;
};

export type TwoFactorDto = {
    email?: null | string;
    userName?: null | string;
    code?: string;
};

export type UpdateRegistrationDto = {
    model?: null | string;
    brand?: string;
    modelYear?: null | number | string;
    frameSize?: number | string;
    frameSizeUnit?: FrameSizeUnit;
    frameType?: FrameType;
    primaryColour?: string;
    secondaryColour?: string;
    city?: string;
    district?: null | string;
    description?: null | string;
};

export type VerifyTwoFactorDto = {
    code?: string;
};

export type RegisterData = {
    body: RegisterDto;
    path: {
        version: string;
    };
    query?: never;
    url: '/api/v{version}/Auth/register';
};

export type RegisterResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type LoginData = {
    body: LoginDto;
    path: {
        version: string;
    };
    query?: never;
    url: '/api/v{version}/Auth/login';
};

export type LoginResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type Verify2FaData = {
    body: TwoFactorDto;
    path: {
        version: string;
    };
    query?: never;
    url: '/api/v{version}/Auth/verify-2fa';
};

export type Verify2FaResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type Setup2FaData = {
    body?: never;
    path: {
        version: string;
    };
    query?: never;
    url: '/api/v{version}/Auth/setup-2fa';
};

export type Setup2FaResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type Eable2FaData = {
    body: VerifyTwoFactorDto;
    path: {
        version: string;
    };
    query?: never;
    url: '/api/v{version}/Auth/enable-2fa';
};

export type Eable2FaResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type Disable2FaData = {
    body?: never;
    path: {
        version: string;
    };
    query?: never;
    url: '/api/v{version}/Auth/disable-2fa';
};

export type Disable2FaResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type RefreshLoginData = {
    body?: null | JwtRefreshRequest;
    path: {
        version: string;
    };
    query?: never;
    url: '/api/v{version}/Auth/refresh';
};

export type RefreshLoginResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type RevokeRefreshData = {
    body?: null | JwtRefreshRequest;
    path: {
        version: string;
    };
    query?: never;
    url: '/api/v{version}/Auth/revoke';
};

export type RevokeRefreshResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type UploadRegistrationImagesData = {
    body: {
        images?: Array<Blob | File>;
    };
    path: {
        registrationId: string;
        version: string;
    };
    query?: never;
    url: '/api/v{version}/Image/upload/{registrationId}';
};

export type UploadRegistrationImagesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type AddRegistrationData = {
    body: CreateRegistrationDto;
    path: {
        version: string;
    };
    query?: never;
    url: '/api/v{version}/Registration/add';
};

export type AddRegistrationResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type MyRegistrationsData = {
    body?: never;
    path: {
        version: string;
    };
    query?: never;
    url: '/api/v{version}/Registration/my-registrations';
};

export type MyRegistrationsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type UserRegistrationsData = {
    body?: never;
    path: {
        userId: string;
        version: string;
    };
    query?: never;
    url: '/api/v{version}/Registration/user-registrations/{userId}';
};

export type UserRegistrationsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type StolenRegistrationsData = {
    body?: never;
    path: {
        version: string;
    };
    query?: {
        Brand?: string;
        City?: string;
        SerialNumber?: string;
    };
    url: '/api/v{version}/Registration/stolen';
};

export type StolenRegistrationsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type StolenUserRegistrationsData = {
    body?: never;
    path: {
        userId: string;
        version: string;
    };
    query?: never;
    url: '/api/v{version}/Registration/stolen/{userId}';
};

export type StolenUserRegistrationsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type SingleRegistrationData = {
    body?: never;
    path: {
        id: string;
        version: string;
    };
    query?: never;
    url: '/api/v{version}/Registration/single/{id}';
};

export type SingleRegistrationResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type MarkStolenData = {
    body?: never;
    path: {
        id: string;
        version: string;
    };
    query?: never;
    url: '/api/v{version}/Registration/mark-stolen/{id}';
};

export type MarkStolenResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type MarkNotStolenData = {
    body?: never;
    path: {
        id: string;
        version: string;
    };
    query?: never;
    url: '/api/v{version}/Registration/mark-not-stolen/{id}';
};

export type MarkNotStolenResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type UpdateRegistrationData = {
    body: UpdateRegistrationDto;
    path: {
        id: string;
        version: string;
    };
    query?: never;
    url: '/api/v{version}/Registration/update/{id}';
};

export type UpdateRegistrationResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteRegistrationData = {
    body?: never;
    path: {
        id: string;
        version: string;
    };
    query?: never;
    url: '/api/v{version}/Registration/delete/{id}';
};

export type DeleteRegistrationResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteMultipleRegistrationData = {
    body: Array<string>;
    path: {
        version: string;
    };
    query?: never;
    url: '/api/v{version}/Registration/delete-multiple';
};

export type DeleteMultipleRegistrationResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type AuthenticatedUserData = {
    body?: never;
    path: {
        version: string;
    };
    query?: never;
    url: '/api/v{version}/User/get-authenticated';
};

export type AuthenticatedUserResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type FinishProfileSetupData = {
    body: FinishProfileSetupDto;
    path: {
        version: string;
    };
    query?: never;
    url: '/api/v{version}/User/finish-profile-setup';
};

export type FinishProfileSetupResponses = {
    /**
     * OK
     */
    200: unknown;
};
